//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activity.DataContext.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public int Id { get; set; }
        public string ActType { get; set; }
        public string InvoiceIdentifier { get; set; }
        public int ActivityId { get; set; }
        public Nullable<int> ReasonId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Reason Reason { get; set; }
    }
}
